development:
  adapter: postgresql
  enconding: unicode
  database: mydatabase
  pool: 5
  username: postgres
  password: Senha123

prodution:
  adapter: postgresql
  enconding: unicode
  database: mydatabase
  pool: 5
  username: postgres
  password: Senha123
